GET http://localhost:5210/applications

###

GET http://localhost:5210/applications/3

###

POST http://localhost:5210/applications
Content-Type: application/json

{
    "companyName": "JP Morgan",
    "title": "DevOps Engineer",
    "seniority": 1,
    "deadline": "2024-02-02",
    "isApplied": false
}

###

PUT http://localhost:5210/applications/5
Content-Type: application/json

{
    "id": 2,
    "companyName": "Apple",
    "title": "Swift Developer",
    "seniority": 3,
    "deadline": "2024-05-12",
    "isApplied": true
}

###

DELETE http://localhost:5210/applications/2